//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace P0045_Nakagawa.w2.Commerce.ExternalAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ftpHost {
            get {
                return ((string)(this["ftpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftpuser")]
        public string ftpUserName {
            get {
                return ((string)(this["ftpUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftpuserpw")]
        public string ftpUserPassword {
            get {
                return ((string)(this["ftpUserPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ftpUseActive {
            get {
                return ((bool)(this["ftpUseActive"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ftpEnableSsl {
            get {
                return ((bool)(this["ftpEnableSsl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("shift_jis")]
        public string ftpUploadFileEncode {
            get {
                return ((string)(this["ftpUploadFileEncode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"""システム受注番号"",""サイト受注番号"",""ショッピングモールコード"",""ショッピングモール名"",""ストアコード"",""ストア名"",""受注日時"",""キャンセル日付"",""顧客コード"",""注文者名"",""注文者名カナ"",""注文者郵便番号"",""注文者住所"",""注文者電話番号"",""注文者FAX番号"",""注文者メールアドレス"",""注文備考"",""社内備考"",""倉庫指示"",""警告内容"",""受注進捗コード"",""受注進捗名"",""決済方法コード"",""決済方法名"",""支払回数コード"",""支払回数名"",""モバイル注文フラグ"",""ポイント"",""クーポン"",""税抜合計"",""消費税"",""税込合計"",""配送料"",""代引手数料"",""請求金額"",""同梱フラグ"",""配送番号"",""楽天用ID"",""配送先名"",""配送先名カナ"",""配送先郵便番号"",""配送先住所"",""配送先電話番号"",""配送先FAX番号"",""配送進捗"",""配送進捗名"",""配送方法"",""配送方法名"",""配送時間"",""配送時間名"",""配送料1"",""代引手数料1"",""ギフトフラグ"",""出荷日"",""出荷確定日"",""配送日"",""荷物番号"",""備考"",""商品番号"",""楽天用ID1"",""商品コード"",""商品名"",""項目選択肢横軸"",""項目選択肢縦軸"",""数量"",""税抜単価"",""単品消費税"",""税抜金額"",""消費税1"",""税込金額"",""社内備考1"",""出荷備考"",""データ登録日時"",""データ更新日時"",""データ更新者コード"",""データ更新者名""")]
        public string header {
            get {
                return ((string)(this["header"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>order_sell</string>
  <string>order_ship</string>
  <string>order_stck</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ftpUploadDirectory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ftpUploadDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".csv")]
        public string ftpUploadFileExtension {
            get {
                return ((string)(this["ftpUploadFileExtension"]));
            }
        }
    }
}
