//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.App.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("w2.App.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- https://pay.amazon.com/jp/developer/documentation/apireference/201753060 --&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : AmazonApiメッセージXML(AmazonApiMessages.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2018 All Rights Reserved.
        ///============================================== [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AmazonApiMessages {
            get {
                return ResourceManager.GetString("AmazonApiMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : 010_Crocs基幹連携用データ取得SQLステートメントXML(Db_ExportData_010_Crocs.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2010 All Rights Reserved.
        ///=========================================================================================================
        ///- [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Db_ExportData_010_Crocs {
            get {
                return ResourceManager.GetString("Db_ExportData_010_Crocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : 注文処理SQLステートメントXML(ExtraOrderData.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2012 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;EntireOrder&gt;
        ///  &lt;!- [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EntireOrder {
            get {
                return ResourceManager.GetString("EntireOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : e-SCOTTレスポンスメッセージ(EScottResponseCodeDetails.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2021 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;EScottRe [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EScottResponseCodeDetails {
            get {
                return ResourceManager.GetString("EScottResponseCodeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : GMO決済エラーメッセージ(GmoMessages.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2011 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;GmoMessages&gt;
        ///  &lt;!-- Exxxx [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GmoMessages {
            get {
                return ResourceManager.GetString("GmoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : NP After Pay Error Message(NPAfterPayErrorMessage.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2020 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;NP [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NPAfterPayErrorMessages {
            get {
                return ResourceManager.GetString("NPAfterPayErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : 注文処理SQLステートメントXML(Order.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2012 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;Order&gt;
        ///  &lt;!-- 注文ステータス更新(外部連 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : Paypay Error Codes (PaypayErrorCodes.xml)
        ///･････････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2021 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///
        ///&lt;ErrorCodes&gt;        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PaypayErrorCodes {
            get {
                return ResourceManager.GetString("PaypayErrorCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      :都道府県表(PrefectureMapping.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2022 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///
        ///&lt;PrefectureMapping&gt;
        ///  &lt;pref [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrefectureMapping {
            get {
                return ResourceManager.GetString("PrefectureMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : リアル店舗在庫処理SQLステートメントXML(RealStock.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2014 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;RealStock&gt;
        ///
        ///  &lt;!- [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RealStock {
            get {
                return ResourceManager.GetString("RealStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SoftbankPaymentMessages&gt;
        ///  &lt;!-- 決済方法 --&gt;
        ///  &lt;PaymentMethods&gt;
        ///    &lt;Message code=&quot;101&quot;&gt;クレジット&lt;/Message&gt;
        ///    &lt;Message code=&quot;304&quot;&gt;Yahoo!ウォレット&lt;/Message&gt;
        ///    &lt;Message code=&quot;305&quot;&gt;楽天あんしん支払サービス&lt;/Message&gt;
        ///    &lt;Message code=&quot;306&quot;&gt;PayPal&lt;/Message&gt;
        ///    &lt;Message code=&quot;309&quot;&gt;リクルートかんたん支払い&lt;/Message&gt;
        ///    &lt;Message code=&quot;401&quot;&gt;docomoケータイ支払い&lt;/Message&gt;
        ///    &lt;Message code=&quot;402&quot;&gt;auかんたん決済&lt;/Message&gt;
        ///    &lt;Message code=&quot;405&quot;&gt;ソフトバンク・ワイモバイルまとめて支払い&lt;/Message&gt;
        ///    &lt;Message code=&quot;701&quot;&gt;Webコンビニ&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SBPSApiMessages {
            get {
                return ResourceManager.GetString("SBPSApiMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SocialPlusMessages&gt;
        ///  &lt;!-- エラー種別 --&gt;
        ///  &lt;ErrorTypes method=&quot;API&quot;&gt;
        ///    &lt;Message code=&quot;1&quot;&gt;無効なAPIキーが指定されているか、存在しないAPIキーです。&lt;/Message&gt;
        ///    &lt;Message code=&quot;2&quot;&gt;ご契約の利用プランでは利用できません。&lt;/Message&gt;
        ///    &lt;Message code=&quot;3&quot;&gt;処理に失敗しました。&lt;/Message&gt;
        ///    &lt;Message code=&quot;4&quot;&gt;無効な認証トークンが指定されているか、存在しない認証トークンです。&lt;/Message&gt;
        ///    &lt;Message code=&quot;5&quot;&gt;必須パラメータが指定されていません。&lt;/Message&gt;
        ///    &lt;Message code=&quot;6&quot;&gt;無効なパラメータが指定されています。&lt;/Message&gt;
        ///    &lt;Message code=&quot;7&quot;&gt;エンティティが存在しません。&lt;/Message&gt;
        ///    &lt;Message code=&quot;8&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SocialPlusErrorMessages {
            get {
                return ResourceManager.GetString("SocialPlusErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : 豕ｨ譁・・逅・QL繧ｹ繝・・繝医Γ繝ｳ繝・ML(Stock.xml)
        /// ・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･・･
        ///  Copyright   : Copyright W2 Co.,Ltd. 2012 All Rights Reserved.
        ///================================ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : ヤマト後払い エラーメッセージ(YamatoKaErrorMessage.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2016 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;YamatoKaErrorMe [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YamatoKaErrorMessages {
            get {
                return ResourceManager.GetString("YamatoKaErrorMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : ヤマトKWC CGメッセージ(YamatoKwcCGMessage.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2016 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;YamatoKwcCGMessage [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YamatoKwcCGMessage {
            get {
                return ResourceManager.GetString("YamatoKwcCGMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : ヤマトKWC エラーメッセージ(YamatoKwcErrorMessage.xml)
        /// ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2016 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;YamatoKwcError [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YamatoKwcErrorMessage {
            get {
                return ResourceManager.GetString("YamatoKwcErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///=========================================================================================================
        ///  Module      : Zeus Api Messages XML (ZeusApiMessages.xml)
        ///  ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///  Copyright   : Copyright W2 Co.,Ltd. 2023 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;ZeusPaymentM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZeusApiMessages {
            get {
                return ResourceManager.GetString("ZeusApiMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;!--
        ///=========================================================================================================
        ///Module      : ゼウスSecureAPIエラーメッセージ(ZeusSecureApiMessages.xml)
        ///･･･････････････････････････････････････････････････････････････････････････････････････････････････････
        ///Copyright   : Copyright W2 Co.,Ltd. 2011 All Rights Reserved.
        ///=========================================================================================================
        ///--&gt;
        ///&lt;ZeusSecureApi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZeusSecureApiMessages {
            get {
                return ResourceManager.GetString("ZeusSecureApiMessages", resourceCulture);
            }
        }
    }
}
