/*
=========================================================================================================
  Module      : 注文ワークフロー共通ページ(OrderWorkflowPage.cs)
  ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
  Copyright   : Copyright W2 Co.,Ltd. 2010 All Rights Reserved.
=========================================================================================================
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using w2.Common.Web;
using w2.Domain.OrderWorkflowSetting;

/// <summary>
/// OrderWorkflowPage の概要の説明です
/// </summary>
public partial class OrderWorkflowPage : OrderPage
{
	// ステータス更新日付条件定数（設定時のドロップダウン値・DBにも条件として格納）
	public const DayOfWeek FIRST_DAY = DayOfWeek.Sunday;
	public const string SEARCH_STATUS_DATE_TODAY = "1";					// 当日
	public const string SEARCH_STATUS_DATE_THISWEEK = "2";				// 今週分
	public const string SEARCH_STATUS_DATE_LASTWEEK = "3";				// 前週分
	public const string SEARCH_STATUS_DATE_THISMONTH = "4";				// 今月分
	public const string SEARCH_STATUS_DATE_LASTMONTH = "5";				// 前月分
	public const string SEARCH_STATUS_DATE_FROMTO = "0";				// 期間指定

	/// <summary>受注ワークフロー用フィールド定数</summary>
	protected static readonly string[] FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE =
	{
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE1,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE2,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE3,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE4,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE5,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE6,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE7,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE8,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE9,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE10,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE11,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE12,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE13,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE14,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE15,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE16,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE17,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE18,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE19,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE20,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE21,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE22,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE23,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE24,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE25,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE26,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE27,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE28,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE29,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE30,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE31,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE32,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE33,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE34,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE35,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE36,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE37,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE38,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE39,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE40,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE41,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE42,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE43,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE44,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE45,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE46,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE47,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE48,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE49,
		Constants.FIELD_ORDERWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE50
	};
	/// <summary>受注ワークフロー用フィールド定数（カセット）</summary>
	protected static readonly string[] FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE =
	{
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE1,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE2,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE3,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE4,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE5,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE6,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE7,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE8,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE9,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE10,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE11,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE12,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE13,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE14,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE15,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE16,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE17,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE18,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE19,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE20,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE21,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE22,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE23,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE24,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE25,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE26,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE27,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE28,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE29,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE30,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE31,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE32,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE33,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE34,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE35,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE36,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE37,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE38,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE39,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE40,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE41,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE42,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE43,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE44,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE45,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE46,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE47,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE48,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE49,
		Constants.FIELD_ORDERWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE50
	};
	/// <summary>定期ワークフロー用フィールド定数</summary>
	protected static readonly string[] FIELD_FIXEDPURCHASEWORKFLOWSETTING_ORDER_EXTEND_STATUS_CHANGE =
	{
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE1,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE2,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE3,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE4,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE5,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE6,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE7,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE8,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE9,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE10,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE11,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE12,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE13,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE14,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE15,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE16,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE17,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE18,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE19,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE20,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE21,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE22,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE23,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE24,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE25,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE26,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE27,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE28,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE29,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE30,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE31,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE32,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE33,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE34,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE35,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE36,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE37,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE38,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE39,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE40,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE41,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE42,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE43,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE44,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE45,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE46,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE47,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE48,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE49,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_FIXED_PURCHASE_EXTEND_STATUS_CHANGE50
	};
	/// <summary>定期ワークフロー用フィールド定数（カセット）</summary>
	protected static readonly string[] FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_ORDER_EXTEND_STATUS_CHANGE =
	{
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE1,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE2,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE3,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE4,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE5,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE6,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE7,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE8,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE9,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE10,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE11,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE12,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE13,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE14,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE15,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE16,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE17,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE18,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE19,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE20,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE21,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE22,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE23,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE24,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE25,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE26,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE27,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE28,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE29,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE30,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE31,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE32,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE33,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE34,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE35,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE36,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE37,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE38,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE39,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE40,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE41,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE42,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE43,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE44,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE45,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE46,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE47,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE48,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE49,
		Constants.FIELD_FIXEDPURCHASEWORKFLOWSETTING_CASSETTE_FIXED_PURCHASE_EXTEND_STATUS_CHANGE50
	};
	protected const string FIELD_RAKUTEN_POINT_USE_TYPE = "rakuten_point_use_type"; // 楽天ポイント利用方法
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS = "return_exchange_update_status";				// 返品更新返金更新日
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_DAY = "return_exchange_update_status_day";		// 返品更新返金更新日（日）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_FROM = "return_exchange_update_status_from";		// 返品更新返金更新日（From）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_TO = "return_exchange_update_status_to";			// 返品更新返金更新日（To）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_HOUR = "return_exchange_update_status_hour";		// 返品更新返金更新日（時）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_MINUTE = "return_exchange_update_status_minute";	// 返品更新返金更新日（分）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_SECOND = "return_exchange_update_status_second";	// 返品更新返金更新日（秒）
	protected const string FIELD_RETURN_EXCHANGE_UPDATE_STATUS_TIME = "return_exchange_update_status_time";		// 返品更新返金更新日（時間）
	protected const string FIELD_UPDATE_STATUS = "update_status";						// ステータス更新日
	protected const string FIELD_UPDATE_STATUS_DAY = "update_status_day";				// ステータス更新日（日）
	protected const string FIELD_UPDATE_STATUS_FROM = "update_status_from";				// ステータス更新日（From）
	protected const string FIELD_UPDATE_STATUS_TO = "update_status_to";					// ステータス更新日（To）
	protected const string FIELD_UPDATE_STATUS_HOUR = "update_status_hour";				// ステータス更新日（時）
	protected const string FIELD_UPDATE_STATUS_MINUTE = "update_status_minute";			// ステータス更新日（分）
	protected const string FIELD_UPDATE_STATUS_SECOND = "update_status_second";			// ステータス更新日（秒）
	protected const string FIELD_UPDATE_STATUS_TIME = "update_status_time";				// ステータス更新日（時間）
	/// <summary>最終与信日時指定を含む</summary>
	protected const string EXTERNAL_PAYMENT_AUTH_DATE_INCLUDE = "include";
	/// <summary>最終与信日時指定を含まない</summary>
	protected const string EXTERNAL_PAYMENT_AUTH_DATE_EXCLUDE = "exclude";
	protected const string SHIPPINGDATE_SPECIFIED = "specified";		// 配送希望日指定あり
	protected const string SHIPPINGDATE_UNSPECIFIED = "unspecified";	// 配送希望日指定なし
	protected const string SHIPPINGDATE_INCLUDE = "include";			// 配送指定を含む
	protected const string SHIPPINGDATE_EXCLUDE = "exclude";			// 配送指定を含まない
	protected const string SHIPPINGDATE_DATEFROM = "shipping_date_from";// Shipping date from 
	protected const string SHIPPINGDATE_DATETO = "shipping_date_to";	// Shipping date to
	protected const char SHIPPINGDATE_SEPARATOR_CHARACTER = '~';		// Shipping date separator character
	protected const string NOVELTY_ID_SPECIFIED = "specified";			// ノベルティID指定あり
	protected const string NOVELTY_ID_UNSPECIFIED = "unspecified";	// ノベルティID指定なし
	protected const string RECOMMEND_ID_SPECIFIED = "specified";			// レコメンドID指定あり
	protected const string RECOMMEND_ID_UNSPECIFIED = "unspecified";	// レコメンドID指定なし
	protected const string SCHEDULED_SHIPPINGDATE_SPECIFIED = "specified";					// Scheduled shipping date specified
	protected const string SCHEDULED_SHIPPINGDATE_UNSPECIFIED = "unspecified";				// Scheduled shipping date unspecified
	protected const string SCHEDULED_SHIPPINGDATE_FROM = "scheduled_shipping_date_from";	// Scheduled shipping date from
	protected const string SCHEDULED_SHIPPINGDATE_TO = "scheduled_shipping_date_to";		// Scheduled shipping date to
	protected const string SCHEDULED_SHIPPINGDATE_INCLUDE = "include";						// Scheduled shipping date include
	protected const string SCHEDULED_SHIPPINGDATE_EXCLUDE = "exclude";						// Scheduled shipping date exclude
	protected const char SCHEDULED_SHIPPINGDATE_SEPARATOR_CHARACTER = '~';					// Scheduled shipping date separator character
	protected const string FIXEDPURCHASE_SHIPPED_COUNT_FROM = "fixedPurchase_shipped_count_from";						// 購入回数(出荷基準)FROM
	protected const string FIXEDPURCHASE_SHIPPED_COUNT_TO = "fixedPurchase_shipped_count_to";						// 購入回数(出荷基準)TO
	protected const string FIXEDPURCHASE_ORDER_COUNT_FROM = "fixedPurchase_order_count_from";						// 購入回数(注文基準)FROM
	protected const string FIXEDPURCHASE_ORDER_COUNT_TO = "fixedPurchase_order_count_to";						// 購入回数(注文基準)TO
	protected const string FIXEDPURCHASE_DATE_CREATED_TO = "fixedPurchase_date_created_to";						// 定期作成日時TO
	protected const string FIXEDPURCHASE_DATE_CHANGED_TO = "fixedPurchase_date_changed_to";						// 定期更新日時TO
	protected const string FIXEDPURCHASE_NEXT_SHIPPING_DATE_FROM = "fixedPurchase_next_shipping_date_from";						// 次回配送日時FROM
	protected const string FIXEDPURCHASE_NEXT_SHIPPING_DATE_TO = "fixedPurchase_next_shipping_date_to";						// 次回配送日時TO
	protected const string FIXEDPURCHASE_NEXT_NEXT_SHIPPING_DATE_FROM = "fixedPurchase_next_next_shipping_date_from";						// 次々回配送日時FROM
	protected const string FIXEDPURCHASE_NEXT_NEXT_SHIPPING_DATE_TO = "fixedPurchase_next_next_shipping_date_to";						// 次々回配送日時TO
	protected const string FIXEDPURCHASE_LAST_ORDER_DATE_TO = "fixedPurchase_last_order_date_to";						// 最終購入日時TO
	protected const string FIXEDPURCHASE_FIXED_PURCHASE_DATE_BGN_TO = "fixedPurchase_date_bgn_to";						// 定期購入開始日時TO
	protected const string FIXEDPURCHASE_RESUME_DATE_FROM = "resume_date_from";	// 定期再開予定日時FROM
	protected const string FIXEDPURCHASE_RESUME_DATE_TO = "resume_date_to";		// 定期再開予定日時TO
	protected const string FIXEDPURCHASE_RESUME_DATE_SPECIFIED = "specified";		// 定期再開予定日指定あり
	protected const string FIXEDPURCHASE_RESUME_DATE_UNSPECIFIED = "unspecified";	// 定期再開予定日指定なし
	protected const char FIXEDPURCHASE_RESUME_DATE_CHARACTER = '~';		// 定期再開予定日分離子文字

	/// <summary>返品交換：決済種別</summary>
	public const string ORDER_RETURN_PAYMENT_KBN = "return_payment";
	/// <summary>外部決済ステータス：クレジットカード</summary>
	protected const string ORDER_EXTERNAL_PAYMENT_STATUS_CARD = "external_payment_status_card";
	/// <summary>返品交換：外部決済ステータス：クレジットカード</summary>
	protected const string ORDER_RETURN_EXTERNAL_PAYMENT_STATUS_CARD = "return_external_payment_status_card";
	/// <summary>外部決済ステータス：コンビニ（後払い）</summary>
	protected const string ORDER_EXTERNAL_PAYMENT_STATUS_CVS = "external_payment_status_cvs";
	/// <summary>返品交換：外部決済ステータス：コンビニ（後払い）</summary>
	protected const string ORDER_RETURN_EXTERNAL_PAYMENT_STATUS_CVS = "return_external_payment_status_cvs";
	/// <summary>外部決済ステータス：台湾後払い</summary>
	protected const string ORDER_EXTERNAL_PAYMENT_STATUS_TRYLINK_AFTERPAY = "external_payment_status_trylink_afterpay";
	/// <summary>返品交換：外部決済ステータス：コンビニ（後払い）</summary>
	protected const string ORDER_RETURN_EXTERNAL_PAYMENT_STATUS_TRYLINK_AFTERPAY = "return_external_payment_status_trylink_afterpay";
	/// <summary>最終与信日指定あり</summary>
	protected const string LAST_AUTH_DATE_SPECIFIED = "specified";
	/// <summary>最終与信日指定なし</summary>
	protected const string LAST_AUTH_DATE_UNSPECIFIED = "unspecified";
	/// <summary>最終与信日 from</summary>
	protected const string LAST_AUTH_DATE_DATEFROM = "last_auth_date_from";
	/// <summary>最終与信日 to</summary>
	protected const string LAST_AUTH_DATE_DATETO = "last_auth_shipping_date_to";
	/// <summary>最終与信日指定区切り文字</summary>
	protected const char LAST_AUTH_DATE_SEPARATOR_CHARACTER = '~';
	/// <summary>モール連携ステータス</summary>
	protected const string FIELD_MALL_LINK_STATUS = "mall_link_status";
	/// <summary>外部連携ステータス</summary>
	protected const string FIELD_EXTERNAL_IMPORT_STATUS = "external_import_status";
	/// <summary>ワークフロー種別：受注ワークフロー</summary>
	protected const string KBN_WORKFLOW_TYPE_ORDER = "order";
	/// <summary>ワークフロー種別：定期台帳ワークフロー</summary>
	protected const string KBN_WORKFLOW_TYPE_FIXEDPURCHASE = "fixed_purchase";
	/// <summary>対象注文種別(通常注文/定期注文)</summary>
	protected const string TARGET_ORDER_TYPE = "target_order_type";

	// リクエスト定数
	/// <summary>並び順</summary>
	protected const string REQUEST_KEY_RETURN_EXCHANGE_SORT_KBN = "return_exchange_sort";
	/// <summary>ワークフロー種別</summary>
	protected const string REQUEST_KEY_WORKFLOW_TYPE = "workflow_type";

	/// <summary>
	/// 注文ワークフロー設定情報データビュー取得
	/// </summary>
	/// <param name="strShopId">店舗ID</param>
	/// <param name="strWorkFlowKbn">ワークフロー区分</param>
	/// <param name="strWorkFlowNo">枝番</param>
	/// <returns>注文ワークフロー設定情報データビュー</returns>
	protected DataView GetOrderWorkflowSetting(string strShopId, string strWorkFlowKbn, string strWorkFlowNo)
	{
		string pageName = null;
		string statementName = null;
		if (this.RequestWorkflowType == KBN_WORKFLOW_TYPE_ORDER)
		{
			pageName = "OrderWorkflowSetting";
			statementName = "GetOrderWorkflowSetting";
		}
		else
		{
			pageName = "FixedPurchaseWorkflowSetting";
			statementName = "GetFixedPurchaseWorkflowSetting";
		}
		using (var accessor = new SqlAccessor())
		using (var statement = new SqlStatement(pageName, statementName))
		{
			var input = new Hashtable
			{
				{ Constants.FIELD_ORDERWORKFLOWSETTING_SHOP_ID, strShopId },
				{ Constants.FIELD_ORDERWORKFLOWSETTING_WORKFLOW_KBN, strWorkFlowKbn },
				{ Constants.FIELD_ORDERWORKFLOWSETTING_WORKFLOW_NO, strWorkFlowNo }
			};

			return statement.SelectSingleStatementWithOC(accessor, input);
		}
	}

	/// <summary>
	/// ワークフロー設定一覧遷移URL作成
	/// </summary>
	/// <param name="searchParameters">検索情報</param>
	/// <param name="isAddPageNumber">ページを付けるかどうかフラグ（ページャ作成の際はfalse）</param>
	/// <param name="pageNumber">ページ番号</param>
	/// <returns>ワークフロー設定一覧遷移URL</returns>
	protected string CreatOrderWorkflowSettingListUrl(Hashtable searchParameters, bool isAddPageNumber, int? pageNumber)
	{
		var url = new UrlCreator(Constants.PATH_ROOT + Constants.PAGE_MANAGER_ORDERWORKFLOWSETTING_LIST)
			.AddParam(Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_KBN, HttpUtility.UrlEncode((string)searchParameters[Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_KBN]))
			.AddParam(Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_NAME, StringUtility.ToEmpty(searchParameters[Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_NAME]))
			.AddParam(Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_VALID_FLG, HttpUtility.UrlEncode((string)searchParameters[Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_VALID_FLG]))
			.AddParam(Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_DETAIL_KBN, HttpUtility.UrlEncode((string)searchParameters[Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_DETAIL_KBN]))
			.AddParam(Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_ADDITIONAL_SEARCH_FLG, HttpUtility.UrlEncode((string)searchParameters[Constants.REQUEST_KEY_ORDERWORKFLOWSETTING_WORKFLOW_ADDITIONAL_SEARCH_FLG]))
			.AddParam(Constants.REQUEST_KEY_SORT_KBN, HttpUtility.UrlEncode((string)searchParameters[Constants.REQUEST_KEY_SORT_KBN]));

		if (isAddPageNumber)
		{
			url.AddParam(Constants.REQUEST_KEY_PAGE_NO, HttpUtility.UrlEncode(
				pageNumber.HasValue
				? pageNumber.ToString()
				: searchParameters[Constants.REQUEST_KEY_PAGE_NO].ToString()));
		}

		return url.CreateUrl();
	}

	/// <summary>
	/// 定期購入ステータス表示用CSS-CLASS取得
	/// </summary>
	/// <param name="fixedPurchaseStatus">定期購入ステータス</param>
	/// <returns>CSS-CLASS</returns>
	public static string GetFixedPurchaseStatusCssClass(string fixedPurchaseStatus)
	{
		switch (fixedPurchaseStatus)
		{
			case Constants.FLG_FIXEDPURCHASE_FIXED_PURCHASE_STATUS_NORMAL:
			case Constants.FLG_FIXEDPURCHASE_FIXED_PURCHASE_STATUS_CANCEL:
			case Constants.FLG_FIXEDPURCHASE_FIXED_PURCHASE_STATUS_CANCEL_TEMP:
				return "";

			default:
				return "notice";
		}
	}

	/// <summary>
	/// 決済ステータス表示用CSS-CLASS取得
	/// </summary>
	/// <param name="paymentStatus">決済ステータス</param>
	/// <returns>CSS-CLASS</returns>
	public static string GetPaymentStatusCssClass(string paymentStatus)
	{
		switch (paymentStatus)
		{
			case Constants.FLG_FIXEDPURCHASE_PAYMENT_STATUS_NORMAL:
				return "";

			default:
				return "notice";
		}
	}

	/// <summary>
	/// 定期購入商品単価取得取得
	/// </summary>
	/// <param name="fixedPurchasePrice">定期購入価格</param>
	/// <param name="memberRankPrice">会員ランク価格</param>
	/// <param name="specialPrice">特別価格</param>
	/// <param name="price">購入価格</param> 
	/// <returns>定期購入商品単価</returns>
	public static string GetFixedPurchaseItemPrice(
		string fixedPurchasePrice, 
		string memberRankPrice,
		string specialPrice,
		string price)
	{
		if (string.IsNullOrEmpty(fixedPurchasePrice) == false) return fixedPurchasePrice;
		if (string.IsNullOrEmpty(memberRankPrice) == false) return memberRankPrice;
		if (string.IsNullOrEmpty(specialPrice) == false) return specialPrice;
		return price;
	}

	/// <summary>
	/// 定期購入商品の価格を計算(単価*数量)
	/// </summary>
	/// <param name="fixedPurchaseItemPrice">定期購入商品単価</param>
	/// <param name="itemQuantity">会員購入商品個数</param>
	/// <returns>定期購入商品合計価格</returns>
	public static decimal CaluculateFixedPurchaseItemPriceSum(string fixedPurchaseItemPrice, string itemQuantity)
	{
		int quantity;
		int.TryParse(itemQuantity, out quantity);
		Decimal price;
		Decimal.TryParse(fixedPurchaseItemPrice, out price);
		var priceSum = quantity * price;
		return priceSum;
	}

	/// <summary>
	/// 注文ワークフロー設定数がユーザー利用可能最大件数より少ないか
	/// </summary>
	/// <returns>注文ワークフロー設定数がユーザー利用可能最大件数より少ないか</returns>
	protected bool IsLessOrderWorkflowSettingThenMaxCount()
	{
		var isLess = ((Constants.ORDERWORKFLOWSETTING_MAXCOUNT.HasValue == false)
			|| (Constants.ORDERWORKFLOWSETTING_MAXCOUNT <= 0)
			|| (this.OrderWorkflowSettingItemsCount < Constants.ORDERWORKFLOWSETTING_MAXCOUNT));
		return isLess;
	}

	/// <summary>リクエストワークフロー種別</summary>
	protected string RequestWorkflowType
	{
		get { return Request[Constants.REQUEST_KEY_WORKFLOW_TYPE]; }
	}

	/// <summary>注文ワークフロー設定総数</summary>
	protected int OrderWorkflowSettingItemsCount
	{
		get { return new OrderWorkflowSettingService().GetTotalOrderWorkflowSettingCount(); }
	}
}
