if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[w2_InvoiceAtodene]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[w2_InvoiceAtodene]
GO
/*
=========================================================================================================
  Module      : AtodeneМуХеВвР┐ЛБПС (w2_InvoiceAtodene.sql)
 еееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееееее
  Copyright   : Copyright W2 Co.,Ltd. 2019 All Rights Reserved.
=========================================================================================================
*/
CREATE TABLE [dbo].[w2_InvoiceAtodene] (
	[order_id] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[zip] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[address1] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[address2] [nvarchar] (25) NOT NULL DEFAULT (N''),
	[companyName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[sectionName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[name] [nvarchar] (21) NOT NULL DEFAULT (N''),
	[siteNameTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[siteName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[shopOrderIdTitle] [nvarchar] (9) NOT NULL DEFAULT (N''),
	[shopOrderId] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[descriptionText1] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[descriptionText2] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[descriptionText3] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[descriptionText4] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[descriptionText5] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billServiceName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billServiceInfo1] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billServiceInfo2] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billServiceInfo3] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billServiceInfo4] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billState1] [nvarchar] (16) NOT NULL DEFAULT (N''),
	[billFirstGreet1] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billFirstGreet2] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billFirstGreet3] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[billFirstGreet4] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[expand1] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand2] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand3] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand4] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand5] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand6] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand7] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand8] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand9] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand10] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[billedAmountTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[billedAmount] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[billedFeeTax] [nvarchar] (14) NOT NULL DEFAULT (N''),
	[billOrderdayTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[shopOrderDate] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[billSendDateTitle] [nvarchar] (7) NOT NULL DEFAULT (N''),
	[billSendDate] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[billDeadlineDateTitle] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[billDeadlineDate] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[transactionIdTitle] [nvarchar] (7) NOT NULL DEFAULT (N''),
	[transactionId] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[billBankInfomation] [nvarchar] (90) NOT NULL DEFAULT (N''),
	[bankNameTitle] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[bankName] [nvarchar] (10) NOT NULL DEFAULT (N''),
	[bankCode] [nvarchar] (6) NOT NULL DEFAULT (N''),
	[branchNameTitle] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[branchName] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[branchCode] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[bankAccountNumberTitle] [nvarchar] (10) NOT NULL DEFAULT (N''),
	[bankAccountKind] [nvarchar] (4) NOT NULL DEFAULT (N''),
	[bankAccountNumber] [nvarchar] (7) NOT NULL DEFAULT (N''),
	[bankAccountNameTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[bankAccountName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[receiptBillDeadlineDate] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[receiptName] [nvarchar] (21) NOT NULL DEFAULT (N''),
	[invoiceBarcode] [nvarchar] (44) NOT NULL DEFAULT (N''),
	[receiptCompanyTitle] [nvarchar] (14) NOT NULL DEFAULT (N''),
	[receiptCompany] [nvarchar] (22) NOT NULL DEFAULT (N''),
	[docketbilledAmount] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[docketCompanyName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[docketSectionName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[docketName] [nvarchar] (21) NOT NULL DEFAULT (N''),
	[docketTransactionIdTitle] [nvarchar] (7) NOT NULL DEFAULT (N''),
	[docketTransactionId] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[voucherCompanyName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[voucherSectionName] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[voucherCustomerFullName] [nvarchar] (21) NOT NULL DEFAULT (N''),
	[voucherTransactionIdTitle] [nvarchar] (7) NOT NULL DEFAULT (N''),
	[voucherTransactionId] [nvarchar] (11) NOT NULL DEFAULT (N''),
	[voucherBilledAmount] [nvarchar] (8) NOT NULL DEFAULT (N''),
	[voucherBilledFeeTax] [nvarchar] (14) NOT NULL DEFAULT (N''),
	[revenueStampRequired] [nvarchar] (6) NOT NULL DEFAULT (N''),
	[goodsTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[goodsAmountTitle] [nvarchar] (3) NOT NULL DEFAULT (N''),
	[goodsPriceTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[goodsSubtotalTitle] [nvarchar] (5) NOT NULL DEFAULT (N''),
	[detailInfomation] [nvarchar] (60) NOT NULL DEFAULT (N''),
	[expand11] [nvarchar] (14) NOT NULL DEFAULT (N''),
	[expand12] [nvarchar] (20) NOT NULL DEFAULT (N''),
	[expand13] [nvarchar] (39) NOT NULL DEFAULT (N''),
	[expand14] [nvarchar] (44) NOT NULL DEFAULT (N''),
	[expand15] [nvarchar] (30) NOT NULL DEFAULT (N''),
	[expand16] [nvarchar] (1) NOT NULL DEFAULT (N''),
	[expand17] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand18] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand19] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[expand20] [nvarchar] (50) NOT NULL DEFAULT (N''),
	[date_created] [datetime] NOT NULL DEFAULT (getdate())
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[w2_InvoiceAtodene] WITH NOCHECK ADD
	CONSTRAINT [PK_w2_InvoiceAtodene] PRIMARY KEY  CLUSTERED
	(
		[order_id]
	) ON [PRIMARY]
GO
