/*
=========================================================================================================
  Module      : 注文関連ファイル取込系メッセージ定数クラス(ImportMessage.cs)
 ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
  Copyright   : Copyright W2 Co.,Ltd. 2017 All Rights Reserved.
=========================================================================================================
*/

namespace w2.App.Common.Order.Import
{
	/// <summary>
	/// 注文関連ファイル取込系メッセージ定数クラス
	/// </summary>
	public class ImportMessage : w2.App.Common.CommerceMessages
	{
		// 注文関連ファイル取込
		public static string ERRMSG_SYSTEM_ERROR = "ERRMSG_SYSTEM_ERROR";
		public static string ERRMSG_UNEXPECTED_ERROR = "ERRMSG_UNEXPECTED_ERROR";
		public static string ERRMSG_DATA_MIGRATION_FILE_UPLOAD_NOT_CSV = "ERRMSG_DATA_MIGRATION_FILE_UPLOAD_NOT_CSV";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NOORDER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_NOORDER_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NOUSER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_NOUSER_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_MULTI_USER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_MULTI_USER_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NAME_NOT_SAME = "ERRMSG_MANAGER_ORDERFILEIMPORT_NAME_NOT_SAME";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NO_FIXED_PURCHASE_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_NO_FIXED_PURCHASE_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_EXIST_FIXED_PURCHASE_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_EXIST_FIXED_PURCHASE_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_THE_OTHER_FIXED_PURCHASE_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_THE_OTHER_FIXED_PURCHASE_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_IRREGULAR_SHIPPING_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_IRREGULAR_SHIPPING_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NOT_EXIST_PAYMENT = "ERRMSG_MANAGER_ORDERFILEIMPORT_NOT_EXIST_PAYMENT";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_SHIPPING_ID_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_SHIPPING_ID_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_SHIPPING_ID_NOT_SAME = "ERRMSG_MANAGER_ORDERFILEIMPORT_SHIPPING_ID_NOT_SAME";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NOT_EXIST_PRODUCT_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_NOT_EXIST_PRODUCT_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DISABLE_PRODUCT_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_DISABLE_PRODUCT_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_MEMBER_RANK_LACK = "ERRMSG_MANAGER_ORDERFILEIMPORT_MEMBER_RANK_LACK";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_MEMBER_RANK_LACK_NAME = "ERRMSG_MANAGER_ORDERFILEIMPORT_MEMBER_RANK_LACK_NAME";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FIXED_PURCHASE_CYCLUS = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FIXED_PURCHASE_CYCLUS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FIXED_PURCHASE = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FIXED_PURCHASE";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_SHIPPING_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_SHIPPING_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_PAYMENT = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_PAYMENT";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_PRODUCT_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_PRODUCT_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_RECEIPT_INPUT_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_RECEIPT_INPUT_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_FROM = "ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_FROM";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_PROVISO = "ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_PROVISO";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PRODUCTSTOCK_NO_FIND = "ERRMSG_MANAGER_ORDERFILEIMPORT_PRODUCTSTOCK_NO_FIND";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DISABLE_PAYMENT = "ERRMSG_MANAGER_ORDERFILEIMPORT_DISABLE_PAYMENT";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_EXTERNAL_PAYMENT_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_EXTERNAL_PAYMENT_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_TEMPORARY_ORDER_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_TEMPORARY_ORDER_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH = "ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_EXPLANATION = "ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_EXPLANATION";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_DOUBLE_EXPLANATION = "ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_DOUBLE_EXPLANATION";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_UKETORU_EXPLANATION = "ERRMSG_MANAGER_ORDERFILEIMPORT_DEFINITION_MISMATCH_UKETORU_EXPLANATION";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_FIELD_LACK = "ERRMSG_MANAGER_ORDERFILEIMPORT_NECCESARY_FIELD_LACK";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_FIELD_OVERLAPPING = "ERRMSG_MANAGER_ORDERFILEIMPORT_FIELD_OVERLAPPING";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_IRREGULAR_DATA = "ERRMSG_MANAGER_ORDERFILEIMPORT_IRREGULAR_DATA";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_REGISTERED_ORDER_DATA = "ERRMSG_MANAGER_ORDERFILEIMPORT_REGISTERED_ORDER_DATA";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_DATA_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_DATA_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_CREATE_ORDER_INFORMATION = "ERRMSG_MANAGER_ORDERFILEIMPORT_CREATE_ORDER_INFORMATION";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_NO_FIND = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_NO_FIND";
		public static string ERRMSG_MANAGER_ORDERFILRIMPORT_ORDER_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILRIMPORT_ORDER_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_FILE_UNSELECTED = "ERRMSG_MANAGER_ORDERFILEIMPORT_FILE_UNSELECTED";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_FILE_UNFIND = "ERRMSG_MANAGER_ORDERFILEIMPORT_FILE_UNFIND";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAST_MONTHS_INFO = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAST_MONTHS_INFO";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_SUCCESS = "ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_SUCCESS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_EXCLUDE_RECORD = "ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_EXCLUDE_RECORD";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ERROR_EXIST = "ERRMSG_MANAGER_ORDERFILEIMPORT_ERROR_EXIST";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ERROR_RECORD_OVERLIMIT = "ERRMSG_MANAGER_ORDERFILEIMPORT_ERROR_RECORD_OVERLIMIT";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FILE_NAME = "ERRMSG_MANAGER_ORDERFILEIMPORT_INVALID_FILE_NAME";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_DATA_EMPTY = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_DATA_EMPTY";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_COLUMN_COUNT_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_COLUMN_COUNT_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_DATE_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_DATE_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_VALUE_TYPE_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_VALUE_TYPE_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_NO_TARGET_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_NO_TARGET_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_MULTI_TARGET_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_MULTI_TARGET_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_MATCHING_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_MATCHING_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_STATUS_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_STATUS_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_STATUS_MULTIERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_STATUS_MULTIERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_UPDATE_SHIPPING_CHECK_NO_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_UPDATE_SHIPPING_CHECK_NO_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_SEND_MAIL_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_SEND_MAIL_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_UPDATE_ORDER_EXTENDSTATUS_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_UPDATE_ORDER_EXTENDSTATUS_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_ORDER_SUCCESS = "ERRMSG_MANAGER_ORDERFILEIMPORT_IMPORT_ORDER_SUCCESS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_ID_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_ID_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_FIXED_PURCHASE_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_FIXED_PURCHASE_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_ORDER_ID_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_ORDER_ID_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_ORDER_FIXED_PURCHASE_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILEIMPORT_PAYMENT_ORDER_FIXED_PURCHASE_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_AMOUNT_AND_DEPOSIT_AMOUNT_NOT_MATCH = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_AMOUNT_AND_DEPOSIT_AMOUNT_NOT_MATCH";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_DOUBLE_DEPOSIT_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_DOUBLE_DEPOSIT_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_CVS_DEF_DSK_PRELIMINARY_PAYMENT_CANCEL = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_CVS_DEF_DSK_PRELIMINARY_PAYMENT_CANCEL";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_CVS_DEF_DSK_PAYMENT_CONFIRMED = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_CVS_DEF_DSK_PAYMENT_CONFIRMED";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_FIXED_PURCHASE_ID_NOT_EXISTS = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_FIXED_PURCHASE_ID_NOT_EXISTS";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_SHIPPING_DATA_EMPTY = "ERRMSG_MANAGER_ORDERFILEIMPORT_SHIPPING_DATA_EMPTY";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_UKETORU_COOPERATION_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_UKETORU_COOPERATION_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_UKETORU_COOPERATION_DUPLICATED_TRACKING = "ERRMSG_MANAGER_ORDERFILEIMPORT_UKETORU_COOPERATION_DUPLICATED_TRACKING";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_BYTE_LENGTH_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_BYTE_LENGTH_ERROR";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ROW_AND_ORDER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_ROW_AND_ORDER_ID";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_APPROPRIATE_ERROR_EXIST = "ERRMSG_MANAGER_ORDERFILEIMPORT_APPROPRIATE_ERROR_EXIST";
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_GET_ENCODING_ERROR = "ERRMSG_MANAGER_ORDERFILEIMPORT_GET_ENCODING_ERROR";
		/// <summary> フィールド名は存在しません。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_FIELDNAME = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_FIELDNAME";
		/// <summary> 取込対象データは0件です。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_NO_ROW = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_NO_ROW";
		/// <summary> 入力したデータの設定値は間違っています。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_CONTENT_FORMAT = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_CONTENT_FORMAT";
		/// <summary> 入力した注文IDは更新されていません。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_ORDER = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_ORDER";
		/// <summary> 入力した注文IDは存在しません。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_ORDER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_WRONG_ORDER_ID";
		/// <summary> 入力した注文IDはキャンセルされていました。 </summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_CANCELED_ORDER_ID = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_CANCELED_ORDER_ID";
		/// <summary>入力した注文ステータスへは更新できません。</summary>
		public static string ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_UNABLE_TO_UPDATE = "ERRMSG_MANAGER_ORDERFILEIMPORT_ORDER_STATUS_UNABLE_TO_UPDATE";
		public static string ERRMSG_MANAGER_GET_INVOICE_ERROR = "ERRMSG_MANAGER_GET_INVOICE_ERROR";
	}
}
