//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.Plugin.P0011_Intercom.Webservice.w2Test
{


	public partial class Redirect2
	{

		/// <summary>
		/// form1 コントロール。
		/// </summary>
		/// <remarks>
		/// 自動生成されたフィールド。
		/// 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
		/// </remarks>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
