//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.Commerce.Batch.ExportCriteoDatas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=w2DB1;database=R5044_Kagome.Develop;uid=sa;pwd=w2Sa")]
        public string SqlConnection {
            get {
                return ((string)(this["SqlConnection"]));
            }
            set {
                this["SqlConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("w2.Commerce.Batch.ExportCriteoDatas")]
        public string Application_Name {
            get {
                return ((string)(this["Application_Name"]));
            }
            set {
                this["Application_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CriteoData.csv")]
        public string FileName {
            get {
                return ((string)(this["FileName"]));
            }
            set {
                this["FileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Logs\\R5044_Kagome.Develop\\w2.Commerce.Batch.ExportCriteoDatas\\Upload\\")]
        public string FileUploadDirPath {
            get {
                return ((string)(this["FileUploadDirPath"]));
            }
            set {
                this["FileUploadDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Logs\\R5044_Kagome.Develop\\w2.Commerce.Batch.ExportCriteoDatas\\")]
        public string Directory_LogFilePath {
            get {
                return ((string)(this["Directory_LogFilePath"]));
            }
            set {
                this["Directory_LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Form/Product/ProductDetail.aspx")]
        public string ProductPage {
            get {
                return ((string)(this["ProductPage"]));
            }
            set {
                this["ProductPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contents/ProductImages/0/")]
        public string ImageRoot {
            get {
                return ((string)(this["ImageRoot"]));
            }
            set {
                this["ImageRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/R5044_Kagome.Develop/Web/w2.Commerce.Front/")]
        public string SiteRoot {
            get {
                return ((string)(this["SiteRoot"]));
            }
            set {
                this["SiteRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Criteo商品フィード出力完了\"")]
        public string MailTitle {
            get {
                return ((string)(this["MailTitle"]));
            }
            set {
                this["MailTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh@w2s.xyz")]
        public string MailFrom {
            get {
                return ((string)(this["MailFrom"]));
            }
            set {
                this["MailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bh@w2s.xyz</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MailTo {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MailTo"]));
            }
            set {
                this["MailTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bh@w2s.xyz</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MailCc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MailCc"]));
            }
            set {
                this["MailCc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bh@w2s.xyz</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MailBcc {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MailBcc"]));
            }
            set {
                this["MailBcc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\wwwroot\\R5044_Kagome.Develop\\Commons\\w2.CustomerResources\\")]
        public string ConfigFileDirPath {
            get {
                return ((string)(this["ConfigFileDirPath"]));
            }
            set {
                this["ConfigFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.100.241,25,Normal,,110,Apop,,")]
        public string Server_Smtp_Settings {
            get {
                return ((string)(this["Server_Smtp_Settings"]));
            }
            set {
                this["Server_Smtp_Settings"] = value;
            }
        }
    }
}
