//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.237
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.237 によって自動生成されました。
// 
#pragma warning disable 1591

namespace w2.Plugin.P0011_Intercom.Webservice.w2Test.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="w2ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class w2Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TestMethodOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserSyncExecuteOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOnetimePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public w2Service() {
            this.Url = global::w2.Plugin.P0011_Intercom.Webservice.w2Test.Properties.Settings.Default.w2_Plugin_P0011_Intercom_Webservice_w2Test_localhost_w2Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TestMethodCompletedEventHandler TestMethodCompleted;
        
        /// <remarks/>
        public event UserSyncExecuteCompletedEventHandler UserSyncExecuteCompleted;
        
        /// <remarks/>
        public event CreateOnetimePasswordCompletedEventHandler CreateOnetimePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestMethod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestMethod(string value) {
            object[] results = this.Invoke("TestMethod", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestMethodAsync(string value) {
            this.TestMethodAsync(value, null);
        }
        
        /// <remarks/>
        public void TestMethodAsync(string value, object userState) {
            if ((this.TestMethodOperationCompleted == null)) {
                this.TestMethodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestMethodOperationCompleted);
            }
            this.InvokeAsync("TestMethod", new object[] {
                        value}, this.TestMethodOperationCompleted, userState);
        }
        
        private void OnTestMethodOperationCompleted(object arg) {
            if ((this.TestMethodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestMethodCompleted(this, new TestMethodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UserSyncExecute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet UserSyncExecute(System.Data.DataSet ds) {
            object[] results = this.Invoke("UserSyncExecute", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void UserSyncExecuteAsync(System.Data.DataSet ds) {
            this.UserSyncExecuteAsync(ds, null);
        }
        
        /// <remarks/>
        public void UserSyncExecuteAsync(System.Data.DataSet ds, object userState) {
            if ((this.UserSyncExecuteOperationCompleted == null)) {
                this.UserSyncExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserSyncExecuteOperationCompleted);
            }
            this.InvokeAsync("UserSyncExecute", new object[] {
                        ds}, this.UserSyncExecuteOperationCompleted, userState);
        }
        
        private void OnUserSyncExecuteOperationCompleted(object arg) {
            if ((this.UserSyncExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserSyncExecuteCompleted(this, new UserSyncExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateOnetimePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet CreateOnetimePassword(System.Data.DataSet ds) {
            object[] results = this.Invoke("CreateOnetimePassword", new object[] {
                        ds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void CreateOnetimePasswordAsync(System.Data.DataSet ds) {
            this.CreateOnetimePasswordAsync(ds, null);
        }
        
        /// <remarks/>
        public void CreateOnetimePasswordAsync(System.Data.DataSet ds, object userState) {
            if ((this.CreateOnetimePasswordOperationCompleted == null)) {
                this.CreateOnetimePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOnetimePasswordOperationCompleted);
            }
            this.InvokeAsync("CreateOnetimePassword", new object[] {
                        ds}, this.CreateOnetimePasswordOperationCompleted, userState);
        }
        
        private void OnCreateOnetimePasswordOperationCompleted(object arg) {
            if ((this.CreateOnetimePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateOnetimePasswordCompleted(this, new CreateOnetimePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TestMethodCompletedEventHandler(object sender, TestMethodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestMethodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestMethodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UserSyncExecuteCompletedEventHandler(object sender, UserSyncExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserSyncExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserSyncExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateOnetimePasswordCompletedEventHandler(object sender, CreateOnetimePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateOnetimePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateOnetimePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591