//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.Commerce.Batch.ImportPublicity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=w2DB1;database=R5044_Kagome.Develop;uid=sa;pwd=w2Sa")]
        public string SqlConnection {
            get {
                return ((string)(this["SqlConnection"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("w2.Commerce.Batch.ImportPublicity")]
        public string Application_Name {
            get {
                return ((string)(this["Application_Name"]));
            }
            set {
                this["Application_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SiteId {
            get {
                return ((string)(this["SiteId"]));
            }
            set {
                this["SiteId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev-zeus.naturelab.co.jp/publicity/webapp.php/artcle/lastmod/")]
        public string Publicity_ManagementServer_Access_UpdatedDateUrl {
            get {
                return ((string)(this["Publicity_ManagementServer_Access_UpdatedDateUrl"]));
            }
            set {
                this["Publicity_ManagementServer_Access_UpdatedDateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev-zeus.naturelab.co.jp/publicity/webapp.php/artcle/xml")]
        public string Publicity_ManagementServer_Access_PublicityXmlUrl {
            get {
                return ((string)(this["Publicity_ManagementServer_Access_PublicityXmlUrl"]));
            }
            set {
                this["Publicity_ManagementServer_Access_PublicityXmlUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\Contents\\Html\\")]
        public string PC_TemplateFileDirPath {
            get {
                return ((string)(this["PC_TemplateFileDirPath"]));
            }
            set {
                this["PC_TemplateFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\Form\\Publicity\\")]
        public string PC_PublicityFileDirPath {
            get {
                return ((string)(this["PC_PublicityFileDirPath"]));
            }
            set {
                this["PC_PublicityFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U121_PUBLICITY_VIEW_TEMPLATE")]
        public string Mobile_PublicityViewTemplate_PageID {
            get {
                return ((string)(this["Mobile_PublicityViewTemplate_PageID"]));
            }
            set {
                this["Mobile_PublicityViewTemplate_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U131_PUBLICITY_ARCHIVE_TEMP")]
        public string Mobile_PublicityArchiveTemplate_PageID {
            get {
                return ((string)(this["Mobile_PublicityArchiveTemplate_PageID"]));
            }
            set {
                this["Mobile_PublicityArchiveTemplate_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U120_PUBLICITY_VIEW")]
        public string Mobile_PublicityView_PageID {
            get {
                return ((string)(this["Mobile_PublicityView_PageID"]));
            }
            set {
                this["Mobile_PublicityView_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U141_PUBLICITY_BACK_TEMP")]
        public string Mobile_PublicityBackNumberTemplate_PageID {
            get {
                return ((string)(this["Mobile_PublicityBackNumberTemplate_PageID"]));
            }
            set {
                this["Mobile_PublicityBackNumberTemplate_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R101_SITTOP")]
        public string Mobile_SiteTop_PageID {
            get {
                return ((string)(this["Mobile_SiteTop_PageID"]));
            }
            set {
                this["Mobile_SiteTop_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U111_PUBLICITY_TOP_TEMPLATE")]
        public string Mobile_PublicityTopTemplate_PageID {
            get {
                return ((string)(this["Mobile_PublicityTopTemplate_PageID"]));
            }
            set {
                this["Mobile_PublicityTopTemplate_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@@yyyyMM@@_PUBLICITY_ARCHIVE")]
        public string Mobile_PublicityArchive_PageID {
            get {
                return ((string)(this["Mobile_PublicityArchive_PageID"]));
            }
            set {
                this["Mobile_PublicityArchive_PageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Logs\\R5044_Kagome.Develop\\w2.Commerce.Batch.ImportPublicity\\")]
        public string Directory_LogFilePath {
            get {
                return ((string)(this["Directory_LogFilePath"]));
            }
            set {
                this["Directory_LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\Contents\\img\\")]
        public string PC_ImageFileDirPath {
            get {
                return ((string)(this["PC_ImageFileDirPath"]));
            }
            set {
                this["PC_ImageFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.MobileFront\\Cnts\\imgs\\")]
        public string Mobile_ImageFileDirPath {
            get {
                return ((string)(this["Mobile_ImageFileDirPath"]));
            }
            set {
                this["Mobile_ImageFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\Contents\\img\\SmartPhone\\")]
        public string SmartPhone_ImageFileDirPath {
            get {
                return ((string)(this["SmartPhone_ImageFileDirPath"]));
            }
            set {
                this["SmartPhone_ImageFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\Contents\\Html\\SmartPhone\\")]
        public string SmartPhone_TemplateFileDirPath {
            get {
                return ((string)(this["SmartPhone_TemplateFileDirPath"]));
            }
            set {
                this["SmartPhone_TemplateFileDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Inetpub\\wwwroot\\R5044_Kagome.Develop\\Web\\w2.Commerce.Front\\SmartPhone\\Form\\Publicity\\")]
        public string SmartPhone_PublicityFileDirPath {
            get {
                return ((string)(this["SmartPhone_PublicityFileDirPath"]));
            }
            set {
                this["SmartPhone_PublicityFileDirPath"] = value;
            }
        }
    }
}
