if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[w2_ConvertToFullWidth]') and OBJECTPROPERTY(id, N'IsScalarFunction') = 1)
drop function [dbo].[w2_ConvertToFullWidth]
GO
/*
=========================================================================================================
  Module      : 半角→全角文字変換関数(w2_ConvertToFullWidth.sql)
 ･･･････････････････････････････････････････････････････････････････････････････････････････････････････
  Copyright   : Copyright W2 Co.,Ltd. 2018 All Rights Reserved.
=========================================================================================================
*/
CREATE FUNCTION dbo.w2_ConvertToFullWidth(
	@s VARCHAR(512)
	)
RETURNS VARCHAR(512) AS
BEGIN
    /* ASCII文字はコード順に処理する */
    SET @s = REPLACE(@s COLLATE Japanese_BIN, ' ', '　')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '!', '！')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '"', '”')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '#', '＃')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '$', '＄')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '%', '％')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '&', '＆')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '''', '’')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '(', '（')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, ')', '）')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '*', '＊')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '+', '＋')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, ',', '，')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '-', '－')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '.', '．')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '/', '／')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '0', '０')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '1', '１')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '2', '２')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '3', '３')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '4', '４')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '5', '５')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '6', '６')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '7', '７')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '8', '８')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '9', '９')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, ':', '：')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, ';', '；')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '<', '＜')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '>', '＞')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '?', '？')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '@', '＠')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'A', 'Ａ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'B', 'Ｂ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'C', 'Ｃ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'D', 'Ｄ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'E', 'Ｅ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'F', 'Ｆ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'G', 'Ｇ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'H', 'Ｈ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'I', 'Ｉ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'J', 'Ｊ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'K', 'Ｋ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'L', 'Ｌ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'M', 'Ｍ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'N', 'Ｎ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'O', 'Ｏ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'P', 'Ｐ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'Q', 'Ｑ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'R', 'Ｒ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'S', 'Ｓ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'T', 'Ｔ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'U', 'Ｕ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'V', 'Ｖ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'W', 'Ｗ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'X', 'Ｘ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'Y', 'Ｙ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'Z', 'Ｚ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '`', '｀')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'a', 'ａ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'b', 'ｂ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'c', 'ｃ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'd', 'ｄ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'e', 'ｅ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'f', 'ｆ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'g', 'ｇ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'h', 'ｈ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'i', 'ｉ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'j', 'ｊ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'k', 'ｋ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'l', 'ｌ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'm', 'ｍ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'n', 'ｎ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'o', 'ｏ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'p', 'ｐ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'q', 'ｑ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'r', 'ｒ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 's', 'ｓ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 't', 'ｔ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'u', 'ｕ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'v', 'ｖ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'w', 'ｗ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'x', 'ｘ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'y', 'ｙ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'z', 'ｚ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '{', '｛')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '|', '｜')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '}', '｝')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '~', '￣')

    /* 濁点・半濁点を先に処理する */
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｶﾞ', 'ガ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｷﾞ', 'ギ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｸﾞ', 'グ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｹﾞ', 'ゲ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｺﾞ', 'ゴ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｻﾞ', 'ザ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｼﾞ', 'ジ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｽﾞ', 'ズ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｾﾞ', 'ゼ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｿﾞ', 'ゾ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾀﾞ', 'ダ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾁﾞ', 'ヂ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾂﾞ', 'ヅ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾃﾞ', 'デ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾄﾞ', 'ド')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾊﾞ', 'バ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾋﾞ', 'ビ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾌﾞ', 'ブ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾍﾞ', 'ベ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾎﾞ', 'ボ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾊﾟ', 'パ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾋﾟ', 'ピ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾌﾟ', 'プ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾍﾟ', 'ペ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾎﾟ', 'ポ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｳﾞ', 'ヴ')
    /* 残りはコード順に処理する */
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '｡', '。')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '｢', '「')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '｣', '」')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, '､', '、')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｦ', 'ヲ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｧ', 'ァ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｨ', 'ィ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｩ', 'ゥ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｪ', 'ェ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｫ', 'ォ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｬ', 'ャ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｭ', 'ュ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｮ', 'ョ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｯ', 'ッ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｰ', 'ー')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｱ', 'ア')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｲ', 'イ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｳ', 'ウ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｴ', 'エ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｵ', 'オ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｶ', 'カ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｷ', 'キ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｸ', 'ク')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｹ', 'ケ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｺ', 'コ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｻ', 'サ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｼ', 'シ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｽ', 'ス')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｾ', 'セ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ｿ', 'ソ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾀ', 'タ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾁ', 'チ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾂ', 'ツ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾃ', 'テ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾄ', 'ト')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾅ', 'ナ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾆ', 'ニ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾇ', 'ヌ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾈ', 'ネ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾉ', 'ノ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾊ', 'ハ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾋ', 'ヒ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾌ', 'フ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾍ', 'ヘ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾎ', 'ホ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾏ', 'マ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾐ', 'ミ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾑ', 'ム')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾒ', 'メ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾓ', 'モ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾔ', 'ヤ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾕ', 'ユ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾖ', 'ヨ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾗ', 'ラ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾘ', 'リ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾙ', 'ル')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾚ', 'レ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾛ', 'ロ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾜ', 'ワ')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾝ', 'ン')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾟ', '゜')
    SET @s = REPLACE(@s COLLATE Japanese_BIN, 'ﾞ', '゛')
    
    RETURN @s
END
